# This workflow will deploy to production
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Deploy to production
on:
  push:
    branches: ["main"]
jobs:
  deploy:
    name: Build image
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "v1.28.0" # default is latest stable
        id: install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::814575821063:role/GithubActionsRole
          aws-region: eu-west-1
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v2
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_SDBX }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SDBX }}
      #     aws-region: eu-west-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: "true"
      # - name: Load secret and save to app.env
      #   run: aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:eu-west-1:814575821063:secret:sandbox/simple_bank-Y2eWwi --query SecretString --output text | jq -r 'to_entries|map("\(.key)=\(.value)")|.[]' > app.env

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: simplebank
          IMAGE_TAG: ${{ github.sha }} # Associate the commit ID to the image as a tag
        run: | # push -a pushed all image tag
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -t $REGISTRY/$REPOSITORY:latest .
          docker push -a $REGISTRY/$REPOSITORY

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region eu-west-1 --name simplebank-rAfHKGtH

      - name: Deploy image to Amazon EKS
        run: |
          kubectl apply -f eks/deployment.yaml
          kubectl apply -f eks/service.yaml
          kubectl apply -f eks/ingress.yaml

#           kubectl apply -f eks/issuer.yaml
